# Generated by Django 2.1.5 on 2019-02-08 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderBT_Cases', '0002_auto_20190208_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='patch_version',
            field=models.ForeignKey(blank=True, help_text='What version of the product will this fix be pushed out?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_version', to='SpiderBT_Cases.ProductVersion', verbose_name='Patched Version'),
        ),
    ]
