# Generated by Django 2.1.5 on 2019-02-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderBT_Cases', '0004_case_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='target_version',
            field=models.ManyToManyField(blank=True, help_text='What version should this case be fixed in?', related_name='target_version', to='SpiderBT_Cases.ProductVersion', verbose_name='Target Version'),
        ),
        migrations.AlterField(
            model_name='case',
            name='identifier',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID of this Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('onhold', 'On Hold'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='open', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='A simple identifier to reference cases.', max_length=10),
        ),
    ]
