# Generated by Django 2.1.5 on 2019-02-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderBT_Cases', '0005_auto_20190210_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='target_version',
        ),
        migrations.AddField(
            model_name='case',
            name='target_version',
            field=models.ForeignKey(blank=True, default=1, help_text='What version should this case be fixed in?', on_delete=django.db.models.deletion.CASCADE, to='SpiderBT_Cases.ProductVersion', verbose_name='Target Version'),
            preserve_default=False,
        ),
    ]
