# Generated by Django 2.1.5 on 2019-02-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderBT_Cases', '0006_auto_20190210_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='target_version',
        ),
    ]
