# Generated by Django 2.1.5 on 2019-02-11 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpiderBT_Cases', '0007_remove_case_target_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='CaseVote',
        ),
    ]
