# Generated by Django 2.1.5 on 2019-02-08 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpiderBT_Cases', '0001_initial'),
        ('SpiderBT_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('development', 'Development'), ('testing', 'Testing'), ('done', 'Done')], default='pending', max_length=50)),
                ('assigned_group', models.ManyToManyField(blank=True, related_name='assigned_group', to='SpiderBT_Users.UserGroup')),
                ('assigned_user', models.ManyToManyField(blank=True, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderBT_Cases.Product')),
                ('target_release', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderBT_Cases.ProductVersion')),
            ],
        ),
    ]
